packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.71.10
  "@trpc/client": ^11.0.0-rc.840
  "@trpc/react-query": ^11.0.0-rc.840
  "@trpc/server": ^11.0.0-rc.840
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.2
  zod: ^3.24.2

catalogs:
  react18:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.0
    "@types/react-dom": ^19.1.1
