packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.23
  "@trpc/client": ^11.0.0-rc.730
  "@trpc/react-query": ^11.0.0-rc.730
  "@trpc/server": ^11.0.0-rc.730
  eslint: ^9.9.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.17
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.18
    "@types/react-dom": ^18.3.5
