packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.66.0
  "@trpc/client": ^11.0.0-rc.768
  "@trpc/react-query": ^11.0.0-rc.768
  "@trpc/server": ^11.0.0-rc.768
  eslint: ^9.20.1
  prettier: ^3.5.0
  tailwindcss: ^3.4.17
  typescript: ^5.7.3
  zod: ^3.24.2

catalogs:
  react18:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3
