packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.69.0
  "@trpc/client": ^11.0.0-rc.839
  "@trpc/react-query": ^11.0.0-rc.839
  "@trpc/server": ^11.0.0-rc.839
  eslint: ^9.22.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.2
  zod: ^3.24.2

catalogs:
  react18:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.11
    "@types/react-dom": ^19.0.4
